FROM nginx:stable-alpine
ARG DOCKER_VERSION
ADD install.sh /usr/share/nginx/html/
ADD docker.bash /usr/share/nginx/html/
ADD docker-$DOCKER_VERSION.tgz /usr/share/nginx/html/docker-$DOCKER_VERSION.tgz
ADD daemon.json /usr/share/nginx/html/