FROM nginx:stable-alpine
ARG DOCKER_VERSION
COPY install.sh /usr/share/nginx/html/
COPY docker.bash /usr/share/nginx/html/
COPY daemon.json /usr/share/nginx/html/
COPY install_docker.sh /usr/share/nginx/html/
COPY docker-$DOCKER_VERSION.tgz /usr/share/nginx/html/